/**
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.dev/license
 */
import * as fs from 'fs';
import * as path from 'path';
import { globSync } from 'tinyglobby';
import { analyzeFileAndEnsureNoCrossImports } from './cross_entry_points_imports';
/**
 * List of known `package.json` fields which provide information about
 * supported package formats and their associated entry paths.
 */
const knownFormatPackageJsonFormatFields = ['main', 'typings', 'module'];
// Main entry-point.
main(process.argv.slice(2));
function main(args) {
    // This utility expects all of its arguments to be specified in a params file generated by
    // bazel (see https://docs.bazel.build/versions/master/skylark/lib/Args.html#use_param_file).
    const paramFilePath = args[0];
    // Bazel params may be surrounded with quotes
    function unquoteParameter(s) {
        return s.replace(/^'(.*)'$/, '$1');
    }
    // Parameters are specified in the file one per line.
    const params = fs.readFileSync(paramFilePath, 'utf-8').split('\n').map(unquoteParameter);
    const [
    // Output directory for the npm package.
    outputDirExecPath, 
    // The package segment of the ng_package rule's label (e.g. 'package/common').
    owningPackageName, 
    // JSON data capturing metadata of the package being built. See `PackageMetadata`.
    metadataArg, 
    // Path to the package's README.md.
    readmeMd, 
    // Path to the package's LICENSE file.
    licenseFile, 
    // List of individual ES2022 modules
    esm2022Arg, 
    // List of static files that should be copied into the package.
    staticFilesArg, 
    // List of all type definitions that need to packaged into the ng_package.
    typeDefinitionsArg, 
    // List of side-effectful entry-points
    sideEffectEntryPointsArg,] = params;
    const esm2022 = JSON.parse(esm2022Arg);
    const typeDefinitions = JSON.parse(typeDefinitionsArg);
    const staticFiles = JSON.parse(staticFilesArg);
    const metadata = JSON.parse(metadataArg);
    const sideEffectEntryPoints = JSON.parse(sideEffectEntryPointsArg);
    if (readmeMd) {
        copyFile(readmeMd, 'README.md');
    }
    if (licenseFile) {
        copyFile(licenseFile, 'LICENSE');
    }
    /**
     * Writes a file with the specified content into the package output.
     * @param outputRelativePath Relative path in the output directory where the
     *   file is written to.
     * @param fileContent Content of the file.
     */
    function writeFile(outputRelativePath, fileContent) {
        const outputPath = path.join(outputDirExecPath, outputRelativePath);
        // Always ensure that the target directory exists.
        fs.mkdirSync(path.dirname(outputPath), { recursive: true });
        fs.writeFileSync(outputPath, fileContent);
    }
    /**
     * Copies a file into the package output to the specified location.
     * @param inputPath File that should be copied.
     * @param outputRelativePath Relative path in the output directory where the
     *   file is written to.
     * @param transform Optional text content transform.
     */
    function copyFile(inputPath, outputRelativePath, transform = (t) => t) {
        const fileContent = fs.readFileSync(inputPath, 'utf8');
        writeFile(outputRelativePath, transform(fileContent));
    }
    /**
     * Gets the relative path for the given file within the owning package. This
     * assumes the file is contained in the owning package.
     *
     * e.g. consider the owning package is `packages/core` and the input file
     * is `packages/core/testing/index.d.ts`. This function would return the
     * relative path as followed: `testing/index.d.ts`.
     */
    function getOwningPackageRelativePath(file) {
        return path.relative(owningPackageName, file.shortPath);
    }
    /** Gets the output-relative path where the typing file is being written to. */
    function getTypingOutputRelativePath(file) {
        // Type definitions are intended to be copied into the package output while preserving the
        // sub-path from the owning package. e.g. a file like `packages/animations/browser/__index.d.ts`
        // will end up being written to `<pkg-out>/browser/index.d.ts`. Note that types are bundled
        // as a separate action in the `ng_package` Starlark rule and prefixed with `__` to avoid
        // conflicts with source `index.d.ts` files. We remove this prefix here.
        return getOwningPackageRelativePath(file).replace(/__index\.d\.ts$/, 'index.d.ts');
    }
    /**
     * Gets the entry-point sub-path from the package root. e.g. if the package name
     * is `@angular/cdk`, then for `@angular/cdk/a11y` just `a11y` would be returned.
     */
    function getEntryPointSubpath(moduleName) {
        return moduleName.slice(`${metadata.npmPackageName}/`.length);
    }
    /**
     * Gets whether the given module name resolves to a secondary entry-point.
     * e.g. if the package name is `@angular/cdk`, then for `@angular/cdk/a11y`
     * this would return `true`.
     */
    function isSecondaryEntryPoint(moduleName) {
        return getEntryPointSubpath(moduleName) !== '';
    }
    const crossEntryPointFailures = esm2022.flatMap((file) => analyzeFileAndEnsureNoCrossImports(file, metadata));
    if (crossEntryPointFailures.length) {
        console.error(crossEntryPointFailures);
        process.exit(1);
    }
    const fesmFiles = globSync('**/*', { cwd: metadata.bundlesOut.path });
    // Copy all FESM files (and their potential shared chunks) into the package output.
    fesmFiles.forEach((f) => copyFile(path.join(metadata.bundlesOut.path, f), f));
    // Copy all type definitions into the package, preserving the sub-path from the
    // owning package. e.g. a file like `packages/animations/browser/__index.d.ts` will
    // end up in `browser/index.d.ts`
    typeDefinitions.forEach((f) => copyFile(f.path, getTypingOutputRelativePath(f), transformRemoveAmdModules));
    for (const file of staticFiles) {
        // We copy all files into the package output while preserving the sub-path from
        // the owning package. e.g. `packages/core/package.json` ends up `<pkg-out>/package.json`.
        const outputRelativePath = getOwningPackageRelativePath(file);
        let content = fs.readFileSync(file.path, 'utf8');
        // Check and modify package.json files as necessary for publishing
        if (path.basename(file.path) === 'package.json') {
            const isPrimaryPackageJson = outputRelativePath === 'package.json';
            const packageJson = JSON.parse(content);
            const packageName = packageJson['name'];
            // Prevent non-primary `package.json` files which would throw-off resolution.
            // Resolution in the package should only be based on the top-level `package.json`.
            if (!isPrimaryPackageJson) {
                throw Error(`Found a nested "package.json" file in the package output: ${file.shortPath}.\n` +
                    `All information of the package should reside in the primary package file.`);
            }
            // Check if the `name` field of the `package.json` files are matching with
            // name of the NPM package. This is an additional safety check.
            if (packageName !== metadata.npmPackageName) {
                throw Error(`Primary "package.json" has mismatching package name. Expected the ` +
                    `package to be named "${metadata.npmPackageName}", but is set to: ${packageName}.`);
            }
            let newPackageJson = insertFormatFieldsIntoPackageJson(outputRelativePath, packageJson, false);
            newPackageJson = updatePrimaryPackageJson(newPackageJson);
            // Update the content with the new `package.json` file content.
            content = JSON.stringify(newPackageJson, null, 2);
        }
        writeFile(outputRelativePath, content);
    }
    /**
     * Inserts or edits properties into the package.json file(s) in the package so that
     * they point to all the right generated artifacts.
     *
     * @param packageJsonOutRelativePath Path where the `package.json` is stored in
     *   the package output.
     * @param parsedPackage Parsed package.json content
     * @param isGeneratedPackageJson Whether the passed package.json has been generated.
     */
    function insertFormatFieldsIntoPackageJson(packageJsonOutRelativePath, parsedPackage, isGeneratedPackageJson) {
        const packageJson = { ...parsedPackage };
        const packageName = packageJson['name'];
        const entryPointInfo = metadata.entryPoints[packageName];
        const packageJsonContainingDir = path.dirname(packageJsonOutRelativePath);
        // If a package json file has been discovered that does not match any
        // entry-point in the metadata, we report a warning as most likely the target
        // is configured incorrectly (e.g. missing `module_name` attribute).
        if (!entryPointInfo) {
            // Ideally we should throw here, as we got an entry point that doesn't
            // have flat module metadata / bundle index, so it may have been an
            // ng_module that's missing a module_name attribute.
            // However, @angular/compiler can't be an ng_module, as it's the internals
            // of the ngc compiler, yet we want to build an ng_package for it.
            // So ignore package.json files when we are missing data.
            console.error('WARNING: no module metadata for package', packageName);
            console.error('   Not updating the package.json file to point to it');
            console.error('   The ng_module for this package is possibly missing the module_name attribute ');
            return packageJson;
        }
        // If we guessed the index paths for a module, and it contains an explicit `package.json`
        // file that already sets format properties, we skip automatic insertion of format
        // properties but report a warning in case properties have been set by accident.
        if (entryPointInfo.guessedPaths &&
            !isGeneratedPackageJson &&
            hasExplicitFormatProperties(packageJson)) {
            console.error('WARNING: `package.json` explicitly sets format properties (like `main`).');
            console.error('    Skipping automatic insertion of format properties as explicit ' +
                'format properties are set.');
            console.error('    Ignore this warning if explicit properties are set intentionally.');
            return packageJson;
        }
        const fesm2022RelativeOutPath = entryPointInfo.fesm2022RelativePath;
        const typingsRelativeOutPath = getTypingOutputRelativePath(entryPointInfo.typingsEntryPoint);
        packageJson.module = normalizePath(path.relative(packageJsonContainingDir, fesm2022RelativeOutPath));
        packageJson.typings = normalizePath(path.relative(packageJsonContainingDir, typingsRelativeOutPath));
        return packageJson;
    }
    /**
     * Updates the primary `package.json` file of the NPM package to specify
     * the module conditional exports and the ESM module type.
     */
    function updatePrimaryPackageJson(packageJson) {
        if (packageJson.type !== undefined && packageJson.type !== 'module') {
            throw Error('The primary "package.json" file of the package sets the "type" field ' +
                'that is controlled by the packager. Please unset it or set `type` to `module`.');
        }
        const newPackageJson = { ...packageJson };
        newPackageJson.type = 'module';
        // The `package.json` file is made publicly accessible for tools that
        // might want to query information from the Angular NPM package.
        insertExportMappingOrError(newPackageJson, './package.json', { default: './package.json' });
        // Capture all entry-points in the `exports` field using the subpath export declarations:
        // https://nodejs.org/api/packages.html#packages_subpath_exports.
        for (const [moduleName, entryPoint] of Object.entries(metadata.entryPoints)) {
            const subpath = isSecondaryEntryPoint(moduleName)
                ? `./${getEntryPointSubpath(moduleName)}`
                : '.';
            const fesm2022OutRelativePath = entryPoint.fesm2022RelativePath;
            const typesOutRelativePath = getTypingOutputRelativePath(entryPoint.typingsEntryPoint);
            // Insert the export mapping for the entry-point. We set `default` to the FESM 2022
            // output, and also set the `types` condition which will be respected by TS 4.5.
            // https://github.com/microsoft/TypeScript/pull/45884.
            insertExportMappingOrError(newPackageJson, subpath, {
                types: normalizePath(typesOutRelativePath),
                // Note: The default conditions needs to be the last one.
                default: normalizePath(fesm2022OutRelativePath),
            });
        }
        checkPackageJsonSideEffects(packageJson);
        return newPackageJson;
    }
    function checkPackageJsonSideEffects(packageJson) {
        // Convenience if there are no side effects, and it's explicitly marked.
        // This is okay and we don't ask the developer to drop the explicit field.
        if (packageJson.sideEffects === false && sideEffectEntryPoints.length === 0) {
            return;
        }
        if (packageJson.sideEffects === true) {
            throw Error('Unexpected `sideEffects` field in `package.json`. ' +
                'Side effects should be fine-grained and marked via the Bazel `side_effect_entry_points` option.');
        }
        const sideEffects = packageJson.sideEffects;
        const neededSideEffects = sideEffectEntryPoints.map((entryPointModule) => `./${metadata.entryPoints[entryPointModule].fesm2022RelativePath}`);
        const missingSideEffects = neededSideEffects.filter((p) => 
        // It's missing, if the whole package is marked as having no side effects.
        sideEffects === false ||
            // Alternatively, it's missing if the explicit list doesn't contain the pattern.
            !(sideEffects ?? []).includes(p));
        if (missingSideEffects.length > 0) {
            throw Error('Missing side effects in `package.json` `sideEffects` field. ' +
                'Please add the following side effect file patterns:\n' +
                missingSideEffects.join('\n - '));
        }
        // Find potential side-effects that refer to our FESM bundles, but aren't part
        // of the `ng_package` known entry points.
        const unexpectedExtra = sideEffects !== false
            ? (sideEffects ?? []).filter((p) => p.includes('fesm2022') && !neededSideEffects.includes(p))
            : [];
        if (unexpectedExtra.length > 0) {
            throw Error('Unexpected side effects in `package.json` `sideEffects` field that is not known to `ng_package`. ' +
                'Please add the side effect entry point to the Bazel `side_effect_entry_points` option. ' +
                'Unexpected patterns:\n' +
                unexpectedExtra.join('\n - '));
        }
    }
    /**
     * Inserts a subpath export mapping into the specified `package.json` object.
     * @throws An error if the mapping is already defined and would conflict.
     */
    function insertExportMappingOrError(packageJson, subpath, mapping) {
        if (packageJson.exports === undefined) {
            packageJson.exports = {};
        }
        if (packageJson.exports[subpath] === undefined) {
            packageJson.exports[subpath] = {};
        }
        const subpathExport = packageJson.exports[subpath];
        // Go through all conditions that should be inserted. If the condition is already
        // manually set of the subpath export, we throw an error. In general, we allow for
        // additional conditions to be set. These will always precede the generated ones.
        for (const conditionName of Object.keys(mapping)) {
            if (subpathExport[conditionName] !== undefined) {
                throw Error(`Found a conflicting export condition for "${subpath}". The "${conditionName}" ` +
                    `condition would be overridden by the packager. Please unset it.`);
            }
            // **Note**: The order of the conditions is preserved even though we are setting
            // the conditions once at a time (the latest assignment will be at the end).
            subpathExport[conditionName] = mapping[conditionName];
        }
    }
    /** Whether the package explicitly sets any of the format properties (like `main`). */
    function hasExplicitFormatProperties(parsedPackage) {
        return Object.keys(parsedPackage).some((fieldName) => knownFormatPackageJsonFormatFields.includes(fieldName));
    }
    /**
     * Normalizes the specified path by replacing backslash separators with Posix
     * forward slash separators.
     */
    function normalizePath(path) {
        const result = path.replace(/\\/g, '/');
        return result.startsWith('.') ? result : `./${result}`;
    }
    /**
     * Strip the named AMD module directive comments.
     *
     * Those are added by Bazel and aren't relevant for our users.
     */
    function transformRemoveAmdModules(dtsText) {
        return dtsText.replace(/^\/\/\/ <amd-module name=.*\/>[\r\n]+/gm, '');
    }
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicGFja2FnZXIuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyIuLi8uLi8uLi8uLi8uLi8uLi8uLi9wYWNrYWdlcy9iYXplbC9zcmMvbmdfcGFja2FnZS9wYWNrYWdlci50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7O0dBTUc7QUFFSCxPQUFPLEtBQUssRUFBRSxNQUFNLElBQUksQ0FBQztBQUN6QixPQUFPLEtBQUssSUFBSSxNQUFNLE1BQU0sQ0FBQztBQUM3QixPQUFPLEVBQUMsUUFBUSxFQUFDLE1BQU0sWUFBWSxDQUFDO0FBR3BDLE9BQU8sRUFBQyxrQ0FBa0MsRUFBQyxNQUFNLDhCQUE4QixDQUFDO0FBRWhGOzs7R0FHRztBQUNILE1BQU0sa0NBQWtDLEdBQUcsQ0FBQyxNQUFNLEVBQUUsU0FBUyxFQUFFLFFBQVEsQ0FBVSxDQUFDO0FBd0JsRixvQkFBb0I7QUFDcEIsSUFBSSxDQUFDLE9BQU8sQ0FBQyxJQUFJLENBQUMsS0FBSyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUM7QUFFNUIsU0FBUyxJQUFJLENBQUMsSUFBYztJQUMxQiwwRkFBMEY7SUFDMUYsNkZBQTZGO0lBQzdGLE1BQU0sYUFBYSxHQUFHLElBQUksQ0FBQyxDQUFDLENBQUMsQ0FBQztJQUU5Qiw2Q0FBNkM7SUFDN0MsU0FBUyxnQkFBZ0IsQ0FBQyxDQUFTO1FBQ2pDLE9BQU8sQ0FBQyxDQUFDLE9BQU8sQ0FBQyxVQUFVLEVBQUUsSUFBSSxDQUFDLENBQUM7SUFDckMsQ0FBQztJQUVELHFEQUFxRDtJQUNyRCxNQUFNLE1BQU0sR0FBRyxFQUFFLENBQUMsWUFBWSxDQUFDLGFBQWEsRUFBRSxPQUFPLENBQUMsQ0FBQyxLQUFLLENBQUMsSUFBSSxDQUFDLENBQUMsR0FBRyxDQUFDLGdCQUFnQixDQUFDLENBQUM7SUFFekYsTUFBTTtJQUNKLHdDQUF3QztJQUN4QyxpQkFBaUI7SUFFakIsOEVBQThFO0lBQzlFLGlCQUFpQjtJQUVqQixrRkFBa0Y7SUFDbEYsV0FBVztJQUVYLG1DQUFtQztJQUNuQyxRQUFRO0lBRVIsc0NBQXNDO0lBQ3RDLFdBQVc7SUFFWCxvQ0FBb0M7SUFDcEMsVUFBVTtJQUVWLCtEQUErRDtJQUMvRCxjQUFjO0lBRWQsMEVBQTBFO0lBQzFFLGtCQUFrQjtJQUVsQixzQ0FBc0M7SUFDdEMsd0JBQXdCLEVBQ3pCLEdBQUcsTUFBTSxDQUFDO0lBRVgsTUFBTSxPQUFPLEdBQUcsSUFBSSxDQUFDLEtBQUssQ0FBQyxVQUFVLENBQW9CLENBQUM7SUFDMUQsTUFBTSxlQUFlLEdBQUcsSUFBSSxDQUFDLEtBQUssQ0FBQyxrQkFBa0IsQ0FBb0IsQ0FBQztJQUMxRSxNQUFNLFdBQVcsR0FBRyxJQUFJLENBQUMsS0FBSyxDQUFDLGNBQWMsQ0FBb0IsQ0FBQztJQUNsRSxNQUFNLFFBQVEsR0FBRyxJQUFJLENBQUMsS0FBSyxDQUFDLFdBQVcsQ0FBb0IsQ0FBQztJQUM1RCxNQUFNLHFCQUFxQixHQUFHLElBQUksQ0FBQyxLQUFLLENBQUMsd0JBQXdCLENBQWEsQ0FBQztJQUUvRSxJQUFJLFFBQVEsRUFBRSxDQUFDO1FBQ2IsUUFBUSxDQUFDLFFBQVEsRUFBRSxXQUFXLENBQUMsQ0FBQztJQUNsQyxDQUFDO0lBRUQsSUFBSSxXQUFXLEVBQUUsQ0FBQztRQUNoQixRQUFRLENBQUMsV0FBVyxFQUFFLFNBQVMsQ0FBQyxDQUFDO0lBQ25DLENBQUM7SUFFRDs7Ozs7T0FLRztJQUNILFNBQVMsU0FBUyxDQUFDLGtCQUEwQixFQUFFLFdBQTRCO1FBQ3pFLE1BQU0sVUFBVSxHQUFHLElBQUksQ0FBQyxJQUFJLENBQUMsaUJBQWlCLEVBQUUsa0JBQWtCLENBQUMsQ0FBQztRQUVwRSxrREFBa0Q7UUFDbEQsRUFBRSxDQUFDLFNBQVMsQ0FBQyxJQUFJLENBQUMsT0FBTyxDQUFDLFVBQVUsQ0FBQyxFQUFFLEVBQUMsU0FBUyxFQUFFLElBQUksRUFBQyxDQUFDLENBQUM7UUFDMUQsRUFBRSxDQUFDLGFBQWEsQ0FBQyxVQUFVLEVBQUUsV0FBVyxDQUFDLENBQUM7SUFDNUMsQ0FBQztJQUVEOzs7Ozs7T0FNRztJQUNILFNBQVMsUUFBUSxDQUNmLFNBQWlCLEVBQ2pCLGtCQUEwQixFQUMxQixZQUFzQyxDQUFDLENBQUMsRUFBRSxFQUFFLENBQUMsQ0FBQztRQUU5QyxNQUFNLFdBQVcsR0FBRyxFQUFFLENBQUMsWUFBWSxDQUFDLFNBQVMsRUFBRSxNQUFNLENBQUMsQ0FBQztRQUN2RCxTQUFTLENBQUMsa0JBQWtCLEVBQUUsU0FBUyxDQUFDLFdBQVcsQ0FBQyxDQUFDLENBQUM7SUFDeEQsQ0FBQztJQUVEOzs7Ozs7O09BT0c7SUFDSCxTQUFTLDRCQUE0QixDQUFDLElBQW1CO1FBQ3ZELE9BQU8sSUFBSSxDQUFDLFFBQVEsQ0FBQyxpQkFBaUIsRUFBRSxJQUFJLENBQUMsU0FBUyxDQUFDLENBQUM7SUFDMUQsQ0FBQztJQUVELCtFQUErRTtJQUMvRSxTQUFTLDJCQUEyQixDQUFDLElBQW1CO1FBQ3RELDBGQUEwRjtRQUMxRixnR0FBZ0c7UUFDaEcsMkZBQTJGO1FBQzNGLHlGQUF5RjtRQUN6Rix3RUFBd0U7UUFDeEUsT0FBTyw0QkFBNEIsQ0FBQyxJQUFJLENBQUMsQ0FBQyxPQUFPLENBQUMsaUJBQWlCLEVBQUUsWUFBWSxDQUFDLENBQUM7SUFDckYsQ0FBQztJQUVEOzs7T0FHRztJQUNILFNBQVMsb0JBQW9CLENBQUMsVUFBa0I7UUFDOUMsT0FBTyxVQUFVLENBQUMsS0FBSyxDQUFDLEdBQUcsUUFBUSxDQUFDLGNBQWMsR0FBRyxDQUFDLE1BQU0sQ0FBQyxDQUFDO0lBQ2hFLENBQUM7SUFFRDs7OztPQUlHO0lBQ0gsU0FBUyxxQkFBcUIsQ0FBQyxVQUFrQjtRQUMvQyxPQUFPLG9CQUFvQixDQUFDLFVBQVUsQ0FBQyxLQUFLLEVBQUUsQ0FBQztJQUNqRCxDQUFDO0lBRUQsTUFBTSx1QkFBdUIsR0FBRyxPQUFPLENBQUMsT0FBTyxDQUFDLENBQUMsSUFBSSxFQUFFLEVBQUUsQ0FDdkQsa0NBQWtDLENBQUMsSUFBSSxFQUFFLFFBQVEsQ0FBQyxDQUNuRCxDQUFDO0lBRUYsSUFBSSx1QkFBdUIsQ0FBQyxNQUFNLEVBQUUsQ0FBQztRQUNuQyxPQUFPLENBQUMsS0FBSyxDQUFDLHVCQUF1QixDQUFDLENBQUM7UUFDdkMsT0FBTyxDQUFDLElBQUksQ0FBQyxDQUFDLENBQUMsQ0FBQztJQUNsQixDQUFDO0lBRUQsTUFBTSxTQUFTLEdBQUcsUUFBUSxDQUFDLE1BQU0sRUFBRSxFQUFDLEdBQUcsRUFBRSxRQUFRLENBQUMsVUFBVSxDQUFDLElBQUksRUFBQyxDQUFDLENBQUM7SUFDcEUsbUZBQW1GO0lBQ25GLFNBQVMsQ0FBQyxPQUFPLENBQUMsQ0FBQyxDQUFDLEVBQUUsRUFBRSxDQUFDLFFBQVEsQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUFDLFFBQVEsQ0FBQyxVQUFVLENBQUMsSUFBSSxFQUFFLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxDQUFDLENBQUM7SUFFOUUsK0VBQStFO0lBQy9FLG1GQUFtRjtJQUNuRixpQ0FBaUM7SUFDakMsZUFBZSxDQUFDLE9BQU8sQ0FBQyxDQUFDLENBQUMsRUFBRSxFQUFFLENBQzVCLFFBQVEsQ0FBQyxDQUFDLENBQUMsSUFBSSxFQUFFLDJCQUEyQixDQUFDLENBQUMsQ0FBQyxFQUFFLHlCQUF5QixDQUFDLENBQzVFLENBQUM7SUFFRixLQUFLLE1BQU0sSUFBSSxJQUFJLFdBQVcsRUFBRSxDQUFDO1FBQy9CLCtFQUErRTtRQUMvRSwwRkFBMEY7UUFDMUYsTUFBTSxrQkFBa0IsR0FBRyw0QkFBNEIsQ0FBQyxJQUFJLENBQUMsQ0FBQztRQUM5RCxJQUFJLE9BQU8sR0FBRyxFQUFFLENBQUMsWUFBWSxDQUFDLElBQUksQ0FBQyxJQUFJLEVBQUUsTUFBTSxDQUFDLENBQUM7UUFFakQsa0VBQWtFO1FBQ2xFLElBQUksSUFBSSxDQUFDLFFBQVEsQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUFDLEtBQUssY0FBYyxFQUFFLENBQUM7WUFDaEQsTUFBTSxvQkFBb0IsR0FBRyxrQkFBa0IsS0FBSyxjQUFjLENBQUM7WUFDbkUsTUFBTSxXQUFXLEdBQUcsSUFBSSxDQUFDLEtBQUssQ0FBQyxPQUFPLENBQWdCLENBQUM7WUFDdkQsTUFBTSxXQUFXLEdBQUcsV0FBVyxDQUFDLE1BQU0sQ0FBQyxDQUFDO1lBRXhDLDZFQUE2RTtZQUM3RSxrRkFBa0Y7WUFDbEYsSUFBSSxDQUFDLG9CQUFvQixFQUFFLENBQUM7Z0JBQzFCLE1BQU0sS0FBSyxDQUNULDZEQUE2RCxJQUFJLENBQUMsU0FBUyxLQUFLO29CQUM5RSwyRUFBMkUsQ0FDOUUsQ0FBQztZQUNKLENBQUM7WUFFRCwwRUFBMEU7WUFDMUUsK0RBQStEO1lBQy9ELElBQUksV0FBVyxLQUFLLFFBQVEsQ0FBQyxjQUFjLEVBQUUsQ0FBQztnQkFDNUMsTUFBTSxLQUFLLENBQ1Qsb0VBQW9FO29CQUNsRSx3QkFBd0IsUUFBUSxDQUFDLGNBQWMscUJBQXFCLFdBQVcsR0FBRyxDQUNyRixDQUFDO1lBQ0osQ0FBQztZQUVELElBQUksY0FBYyxHQUFHLGlDQUFpQyxDQUNwRCxrQkFBa0IsRUFDbEIsV0FBVyxFQUNYLEtBQUssQ0FDTixDQUFDO1lBRUYsY0FBYyxHQUFHLHdCQUF3QixDQUFDLGNBQWMsQ0FBQyxDQUFDO1lBRTFELCtEQUErRDtZQUMvRCxPQUFPLEdBQUcsSUFBSSxDQUFDLFNBQVMsQ0FBQyxjQUFjLEVBQUUsSUFBSSxFQUFFLENBQUMsQ0FBQyxDQUFDO1FBQ3BELENBQUM7UUFFRCxTQUFTLENBQUMsa0JBQWtCLEVBQUUsT0FBTyxDQUFDLENBQUM7SUFDekMsQ0FBQztJQUVEOzs7Ozs7OztPQVFHO0lBQ0gsU0FBUyxpQ0FBaUMsQ0FDeEMsMEJBQWtDLEVBQ2xDLGFBQW9DLEVBQ3BDLHNCQUErQjtRQUUvQixNQUFNLFdBQVcsR0FBZ0IsRUFBQyxHQUFHLGFBQWEsRUFBQyxDQUFDO1FBQ3BELE1BQU0sV0FBVyxHQUFHLFdBQVcsQ0FBQyxNQUFNLENBQUMsQ0FBQztRQUN4QyxNQUFNLGNBQWMsR0FBRyxRQUFRLENBQUMsV0FBVyxDQUFDLFdBQVcsQ0FBQyxDQUFDO1FBQ3pELE1BQU0sd0JBQXdCLEdBQUcsSUFBSSxDQUFDLE9BQU8sQ0FBQywwQkFBMEIsQ0FBQyxDQUFDO1FBRTFFLHFFQUFxRTtRQUNyRSw2RUFBNkU7UUFDN0Usb0VBQW9FO1FBQ3BFLElBQUksQ0FBQyxjQUFjLEVBQUUsQ0FBQztZQUNwQixzRUFBc0U7WUFDdEUsbUVBQW1FO1lBQ25FLG9EQUFvRDtZQUNwRCwwRUFBMEU7WUFDMUUsa0VBQWtFO1lBQ2xFLHlEQUF5RDtZQUN6RCxPQUFPLENBQUMsS0FBSyxDQUFDLHlDQUF5QyxFQUFFLFdBQVcsQ0FBQyxDQUFDO1lBQ3RFLE9BQU8sQ0FBQyxLQUFLLENBQUMsc0RBQXNELENBQUMsQ0FBQztZQUN0RSxPQUFPLENBQUMsS0FBSyxDQUNYLGtGQUFrRixDQUNuRixDQUFDO1lBQ0YsT0FBTyxXQUFXLENBQUM7UUFDckIsQ0FBQztRQUVELHlGQUF5RjtRQUN6RixrRkFBa0Y7UUFDbEYsZ0ZBQWdGO1FBQ2hGLElBQ0UsY0FBYyxDQUFDLFlBQVk7WUFDM0IsQ0FBQyxzQkFBc0I7WUFDdkIsMkJBQTJCLENBQUMsV0FBVyxDQUFDLEVBQ3hDLENBQUM7WUFDRCxPQUFPLENBQUMsS0FBSyxDQUFDLDBFQUEwRSxDQUFDLENBQUM7WUFDMUYsT0FBTyxDQUFDLEtBQUssQ0FDWCxvRUFBb0U7Z0JBQ2xFLDRCQUE0QixDQUMvQixDQUFDO1lBQ0YsT0FBTyxDQUFDLEtBQUssQ0FBQyx1RUFBdUUsQ0FBQyxDQUFDO1lBQ3ZGLE9BQU8sV0FBVyxDQUFDO1FBQ3JCLENBQUM7UUFFRCxNQUFNLHVCQUF1QixHQUFHLGNBQWMsQ0FBQyxvQkFBb0IsQ0FBQztRQUNwRSxNQUFNLHNCQUFzQixHQUFHLDJCQUEyQixDQUFDLGNBQWMsQ0FBQyxpQkFBaUIsQ0FBQyxDQUFDO1FBRTdGLFdBQVcsQ0FBQyxNQUFNLEdBQUcsYUFBYSxDQUNoQyxJQUFJLENBQUMsUUFBUSxDQUFDLHdCQUF3QixFQUFFLHVCQUF1QixDQUFDLENBQ2pFLENBQUM7UUFDRixXQUFXLENBQUMsT0FBTyxHQUFHLGFBQWEsQ0FDakMsSUFBSSxDQUFDLFFBQVEsQ0FBQyx3QkFBd0IsRUFBRSxzQkFBc0IsQ0FBQyxDQUNoRSxDQUFDO1FBRUYsT0FBTyxXQUFXLENBQUM7SUFDckIsQ0FBQztJQUVEOzs7T0FHRztJQUNILFNBQVMsd0JBQXdCLENBQUMsV0FBa0M7UUFDbEUsSUFBSSxXQUFXLENBQUMsSUFBSSxLQUFLLFNBQVMsSUFBSSxXQUFXLENBQUMsSUFBSSxLQUFLLFFBQVEsRUFBRSxDQUFDO1lBQ3BFLE1BQU0sS0FBSyxDQUNULHVFQUF1RTtnQkFDckUsZ0ZBQWdGLENBQ25GLENBQUM7UUFDSixDQUFDO1FBRUQsTUFBTSxjQUFjLEdBQWdCLEVBQUMsR0FBRyxXQUFXLEVBQUMsQ0FBQztRQUVyRCxjQUFjLENBQUMsSUFBSSxHQUFHLFFBQVEsQ0FBQztRQUUvQixxRUFBcUU7UUFDckUsZ0VBQWdFO1FBQ2hFLDBCQUEwQixDQUFDLGNBQWMsRUFBRSxnQkFBZ0IsRUFBRSxFQUFDLE9BQU8sRUFBRSxnQkFBZ0IsRUFBQyxDQUFDLENBQUM7UUFFMUYseUZBQXlGO1FBQ3pGLGlFQUFpRTtRQUNqRSxLQUFLLE1BQU0sQ0FBQyxVQUFVLEVBQUUsVUFBVSxDQUFDLElBQUksTUFBTSxDQUFDLE9BQU8sQ0FBQyxRQUFRLENBQUMsV0FBVyxDQUFDLEVBQUUsQ0FBQztZQUM1RSxNQUFNLE9BQU8sR0FBRyxxQkFBcUIsQ0FBQyxVQUFVLENBQUM7Z0JBQy9DLENBQUMsQ0FBQyxLQUFLLG9CQUFvQixDQUFDLFVBQVUsQ0FBQyxFQUFFO2dCQUN6QyxDQUFDLENBQUMsR0FBRyxDQUFDO1lBQ1IsTUFBTSx1QkFBdUIsR0FBRyxVQUFVLENBQUMsb0JBQW9CLENBQUM7WUFDaEUsTUFBTSxvQkFBb0IsR0FBRywyQkFBMkIsQ0FBQyxVQUFVLENBQUMsaUJBQWlCLENBQUMsQ0FBQztZQUV2RixtRkFBbUY7WUFDbkYsZ0ZBQWdGO1lBQ2hGLHNEQUFzRDtZQUN0RCwwQkFBMEIsQ0FBQyxjQUFjLEVBQUUsT0FBTyxFQUFFO2dCQUNsRCxLQUFLLEVBQUUsYUFBYSxDQUFDLG9CQUFvQixDQUFDO2dCQUMxQyx5REFBeUQ7Z0JBQ3pELE9BQU8sRUFBRSxhQUFhLENBQUMsdUJBQXVCLENBQUM7YUFDaEQsQ0FBQyxDQUFDO1FBQ0wsQ0FBQztRQUVELDJCQUEyQixDQUFDLFdBQVcsQ0FBQyxDQUFDO1FBRXpDLE9BQU8sY0FBYyxDQUFDO0lBQ3hCLENBQUM7SUFFRCxTQUFTLDJCQUEyQixDQUFDLFdBQXdCO1FBQzNELHdFQUF3RTtRQUN4RSwwRUFBMEU7UUFDMUUsSUFBSSxXQUFXLENBQUMsV0FBVyxLQUFLLEtBQUssSUFBSSxxQkFBcUIsQ0FBQyxNQUFNLEtBQUssQ0FBQyxFQUFFLENBQUM7WUFDNUUsT0FBTztRQUNULENBQUM7UUFFRCxJQUFJLFdBQVcsQ0FBQyxXQUFXLEtBQUssSUFBSSxFQUFFLENBQUM7WUFDckMsTUFBTSxLQUFLLENBQ1Qsb0RBQW9EO2dCQUNsRCxpR0FBaUcsQ0FDcEcsQ0FBQztRQUNKLENBQUM7UUFFRCxNQUFNLFdBQVcsR0FBRyxXQUFXLENBQUMsV0FBMkMsQ0FBQztRQUM1RSxNQUFNLGlCQUFpQixHQUFHLHFCQUFxQixDQUFDLEdBQUcsQ0FDakQsQ0FBQyxnQkFBZ0IsRUFBRSxFQUFFLENBQUMsS0FBSyxRQUFRLENBQUMsV0FBVyxDQUFDLGdCQUFnQixDQUFDLENBQUMsb0JBQW9CLEVBQUUsQ0FDekYsQ0FBQztRQUNGLE1BQU0sa0JBQWtCLEdBQUcsaUJBQWlCLENBQUMsTUFBTSxDQUNqRCxDQUFDLENBQUMsRUFBRSxFQUFFO1FBQ0osMEVBQTBFO1FBQzFFLFdBQVcsS0FBSyxLQUFLO1lBQ3JCLGdGQUFnRjtZQUNoRixDQUFDLENBQUMsV0FBVyxJQUFJLEVBQUUsQ0FBQyxDQUFDLFFBQVEsQ0FBQyxDQUFDLENBQUMsQ0FDbkMsQ0FBQztRQUVGLElBQUksa0JBQWtCLENBQUMsTUFBTSxHQUFHLENBQUMsRUFBRSxDQUFDO1lBQ2xDLE1BQU0sS0FBSyxDQUNULDhEQUE4RDtnQkFDNUQsdURBQXVEO2dCQUN2RCxrQkFBa0IsQ0FBQyxJQUFJLENBQUMsT0FBTyxDQUFDLENBQ25DLENBQUM7UUFDSixDQUFDO1FBRUQsOEVBQThFO1FBQzlFLDBDQUEwQztRQUMxQyxNQUFNLGVBQWUsR0FDbkIsV0FBVyxLQUFLLEtBQUs7WUFDbkIsQ0FBQyxDQUFDLENBQUMsV0FBVyxJQUFJLEVBQUUsQ0FBQyxDQUFDLE1BQU0sQ0FDeEIsQ0FBQyxDQUFDLEVBQUUsRUFBRSxDQUFDLENBQUMsQ0FBQyxRQUFRLENBQUMsVUFBVSxDQUFDLElBQUksQ0FBQyxpQkFBaUIsQ0FBQyxRQUFRLENBQUMsQ0FBQyxDQUFDLENBQ2hFO1lBQ0gsQ0FBQyxDQUFDLEVBQUUsQ0FBQztRQUNULElBQUksZUFBZSxDQUFDLE1BQU0sR0FBRyxDQUFDLEVBQUUsQ0FBQztZQUMvQixNQUFNLEtBQUssQ0FDVCxtR0FBbUc7Z0JBQ2pHLHlGQUF5RjtnQkFDekYsd0JBQXdCO2dCQUN4QixlQUFlLENBQUMsSUFBSSxDQUFDLE9BQU8sQ0FBQyxDQUNoQyxDQUFDO1FBQ0osQ0FBQztJQUNILENBQUM7SUFFRDs7O09BR0c7SUFDSCxTQUFTLDBCQUEwQixDQUNqQyxXQUF3QixFQUN4QixPQUFlLEVBQ2YsT0FBMEI7UUFFMUIsSUFBSSxXQUFXLENBQUMsT0FBTyxLQUFLLFNBQVMsRUFBRSxDQUFDO1lBQ3RDLFdBQVcsQ0FBQyxPQUFPLEdBQUcsRUFBRSxDQUFDO1FBQzNCLENBQUM7UUFDRCxJQUFJLFdBQVcsQ0FBQyxPQUFPLENBQUMsT0FBTyxDQUFDLEtBQUssU0FBUyxFQUFFLENBQUM7WUFDL0MsV0FBVyxDQUFDLE9BQU8sQ0FBQyxPQUFPLENBQUMsR0FBRyxFQUFFLENBQUM7UUFDcEMsQ0FBQztRQUVELE1BQU0sYUFBYSxHQUFHLFdBQVcsQ0FBQyxPQUFPLENBQUMsT0FBTyxDQUFDLENBQUM7UUFFbkQsaUZBQWlGO1FBQ2pGLGtGQUFrRjtRQUNsRixpRkFBaUY7UUFDakYsS0FBSyxNQUFNLGFBQWEsSUFBSSxNQUFNLENBQUMsSUFBSSxDQUFDLE9BQU8sQ0FBOEIsRUFBRSxDQUFDO1lBQzlFLElBQUksYUFBYSxDQUFDLGFBQWEsQ0FBQyxLQUFLLFNBQVMsRUFBRSxDQUFDO2dCQUMvQyxNQUFNLEtBQUssQ0FDVCw2Q0FBNkMsT0FBTyxXQUFXLGFBQWEsSUFBSTtvQkFDOUUsaUVBQWlFLENBQ3BFLENBQUM7WUFDSixDQUFDO1lBRUQsZ0ZBQWdGO1lBQ2hGLDRFQUE0RTtZQUM1RSxhQUFhLENBQUMsYUFBYSxDQUFDLEdBQUcsT0FBTyxDQUFDLGFBQWEsQ0FBQyxDQUFDO1FBQ3hELENBQUM7SUFDSCxDQUFDO0lBRUQsc0ZBQXNGO0lBQ3RGLFNBQVMsMkJBQTJCLENBQUMsYUFBb0M7UUFDdkUsT0FBTyxNQUFNLENBQUMsSUFBSSxDQUFDLGFBQWEsQ0FBQyxDQUFDLElBQUksQ0FBQyxDQUFDLFNBQWlCLEVBQUUsRUFBRSxDQUMzRCxrQ0FBa0MsQ0FBQyxRQUFRLENBQUMsU0FBeUMsQ0FBQyxDQUN2RixDQUFDO0lBQ0osQ0FBQztJQUVEOzs7T0FHRztJQUNILFNBQVMsYUFBYSxDQUFDLElBQVk7UUFDakMsTUFBTSxNQUFNLEdBQUcsSUFBSSxDQUFDLE9BQU8sQ0FBQyxLQUFLLEVBQUUsR0FBRyxDQUFDLENBQUM7UUFDeEMsT0FBTyxNQUFNLENBQUMsVUFBVSxDQUFDLEdBQUcsQ0FBQyxDQUFDLENBQUMsQ0FBQyxNQUFNLENBQUMsQ0FBQyxDQUFDLEtBQUssTUFBTSxFQUFFLENBQUM7SUFDekQsQ0FBQztJQUVEOzs7O09BSUc7SUFDSCxTQUFTLHlCQUF5QixDQUFDLE9BQWU7UUFDaEQsT0FBTyxPQUFPLENBQUMsT0FBTyxDQUFDLHlDQUF5QyxFQUFFLEVBQUUsQ0FBQyxDQUFDO0lBQ3hFLENBQUM7QUFDSCxDQUFDIiwic291cmNlc0NvbnRlbnQiOlsiLyoqXG4gKiBAbGljZW5zZVxuICogQ29weXJpZ2h0IEdvb2dsZSBMTEMgQWxsIFJpZ2h0cyBSZXNlcnZlZC5cbiAqXG4gKiBVc2Ugb2YgdGhpcyBzb3VyY2UgY29kZSBpcyBnb3Zlcm5lZCBieSBhbiBNSVQtc3R5bGUgbGljZW5zZSB0aGF0IGNhbiBiZVxuICogZm91bmQgaW4gdGhlIExJQ0VOU0UgZmlsZSBhdCBodHRwczovL2FuZ3VsYXIuZGV2L2xpY2Vuc2VcbiAqL1xuXG5pbXBvcnQgKiBhcyBmcyBmcm9tICdmcyc7XG5pbXBvcnQgKiBhcyBwYXRoIGZyb20gJ3BhdGgnO1xuaW1wb3J0IHtnbG9iU3luY30gZnJvbSAndGlueWdsb2JieSc7XG5cbmltcG9ydCB7QmF6ZWxGaWxlSW5mbywgUGFja2FnZU1ldGFkYXRhfSBmcm9tICcuL2FwaSc7XG5pbXBvcnQge2FuYWx5emVGaWxlQW5kRW5zdXJlTm9Dcm9zc0ltcG9ydHN9IGZyb20gJy4vY3Jvc3NfZW50cnlfcG9pbnRzX2ltcG9ydHMnO1xuXG4vKipcbiAqIExpc3Qgb2Yga25vd24gYHBhY2thZ2UuanNvbmAgZmllbGRzIHdoaWNoIHByb3ZpZGUgaW5mb3JtYXRpb24gYWJvdXRcbiAqIHN1cHBvcnRlZCBwYWNrYWdlIGZvcm1hdHMgYW5kIHRoZWlyIGFzc29jaWF0ZWQgZW50cnkgcGF0aHMuXG4gKi9cbmNvbnN0IGtub3duRm9ybWF0UGFja2FnZUpzb25Gb3JtYXRGaWVsZHMgPSBbJ21haW4nLCAndHlwaW5ncycsICdtb2R1bGUnXSBhcyBjb25zdDtcblxuLyoqIFVuaW9uIHR5cGUgbWF0Y2hpbmcga25vd24gYHBhY2thZ2UuanNvbmAgZm9ybWF0IGZpZWxkcy4gKi9cbnR5cGUgS25vd25QYWNrYWdlSnNvbkZvcm1hdEZpZWxkcyA9ICh0eXBlb2Yga25vd25Gb3JtYXRQYWNrYWdlSnNvbkZvcm1hdEZpZWxkcylbbnVtYmVyXTtcblxuLyoqXG4gKiBUeXBlIGRlc2NyaWJpbmcgdGhlIGNvbmRpdGlvbmFsIGV4cG9ydHMgZGVzY3JpcHRvciBmb3IgYW4gZW50cnktcG9pbnQuXG4gKiBodHRwczovL25vZGVqcy5vcmcvYXBpL3BhY2thZ2VzLmh0bWwjcGFja2FnZXNfY29uZGl0aW9uYWxfZXhwb3J0c1xuICovXG50eXBlIENvbmRpdGlvbmFsRXhwb3J0ID0ge1xuICB0eXBlcz86IHN0cmluZztcbiAgZGVmYXVsdD86IHN0cmluZztcbn07XG5cbi8qKiBUeXBlIGRlc2NyaWJpbmcgYSBgcGFja2FnZS5qc29uYCB0aGUgcGFja2FnZXIgZGVhbHMgd2l0aC4gKi9cbnR5cGUgUGFja2FnZUpzb24gPSB7XG4gIFtrZXkgaW4gS25vd25QYWNrYWdlSnNvbkZvcm1hdEZpZWxkc10/OiBzdHJpbmc7XG59ICYge1xuICBuYW1lOiBzdHJpbmc7XG4gIHR5cGU/OiBzdHJpbmc7XG4gIHNpZGVFZmZlY3RzPzogc3RyaW5nW10gfCBib29sZWFuO1xuICBleHBvcnRzPzogUmVjb3JkPHN0cmluZywgQ29uZGl0aW9uYWxFeHBvcnQ+O1xufTtcblxuLy8gTWFpbiBlbnRyeS1wb2ludC5cbm1haW4ocHJvY2Vzcy5hcmd2LnNsaWNlKDIpKTtcblxuZnVuY3Rpb24gbWFpbihhcmdzOiBzdHJpbmdbXSk6IHZvaWQge1xuICAvLyBUaGlzIHV0aWxpdHkgZXhwZWN0cyBhbGwgb2YgaXRzIGFyZ3VtZW50cyB0byBiZSBzcGVjaWZpZWQgaW4gYSBwYXJhbXMgZmlsZSBnZW5lcmF0ZWQgYnlcbiAgLy8gYmF6ZWwgKHNlZSBodHRwczovL2RvY3MuYmF6ZWwuYnVpbGQvdmVyc2lvbnMvbWFzdGVyL3NreWxhcmsvbGliL0FyZ3MuaHRtbCN1c2VfcGFyYW1fZmlsZSkuXG4gIGNvbnN0IHBhcmFtRmlsZVBhdGggPSBhcmdzWzBdO1xuXG4gIC8vIEJhemVsIHBhcmFtcyBtYXkgYmUgc3Vycm91bmRlZCB3aXRoIHF1b3Rlc1xuICBmdW5jdGlvbiB1bnF1b3RlUGFyYW1ldGVyKHM6IHN0cmluZykge1xuICAgIHJldHVybiBzLnJlcGxhY2UoL14nKC4qKSckLywgJyQxJyk7XG4gIH1cblxuICAvLyBQYXJhbWV0ZXJzIGFyZSBzcGVjaWZpZWQgaW4gdGhlIGZpbGUgb25lIHBlciBsaW5lLlxuICBjb25zdCBwYXJhbXMgPSBmcy5yZWFkRmlsZVN5bmMocGFyYW1GaWxlUGF0aCwgJ3V0Zi04Jykuc3BsaXQoJ1xcbicpLm1hcCh1bnF1b3RlUGFyYW1ldGVyKTtcblxuICBjb25zdCBbXG4gICAgLy8gT3V0cHV0IGRpcmVjdG9yeSBmb3IgdGhlIG5wbSBwYWNrYWdlLlxuICAgIG91dHB1dERpckV4ZWNQYXRoLFxuXG4gICAgLy8gVGhlIHBhY2thZ2Ugc2VnbWVudCBvZiB0aGUgbmdfcGFja2FnZSBydWxlJ3MgbGFiZWwgKGUuZy4gJ3BhY2thZ2UvY29tbW9uJykuXG4gICAgb3duaW5nUGFja2FnZU5hbWUsXG5cbiAgICAvLyBKU09OIGRhdGEgY2FwdHVyaW5nIG1ldGFkYXRhIG9mIHRoZSBwYWNrYWdlIGJlaW5nIGJ1aWx0LiBTZWUgYFBhY2thZ2VNZXRhZGF0YWAuXG4gICAgbWV0YWRhdGFBcmcsXG5cbiAgICAvLyBQYXRoIHRvIHRoZSBwYWNrYWdlJ3MgUkVBRE1FLm1kLlxuICAgIHJlYWRtZU1kLFxuXG4gICAgLy8gUGF0aCB0byB0aGUgcGFja2FnZSdzIExJQ0VOU0UgZmlsZS5cbiAgICBsaWNlbnNlRmlsZSxcblxuICAgIC8vIExpc3Qgb2YgaW5kaXZpZHVhbCBFUzIwMjIgbW9kdWxlc1xuICAgIGVzbTIwMjJBcmcsXG5cbiAgICAvLyBMaXN0IG9mIHN0YXRpYyBmaWxlcyB0aGF0IHNob3VsZCBiZSBjb3BpZWQgaW50byB0aGUgcGFja2FnZS5cbiAgICBzdGF0aWNGaWxlc0FyZyxcblxuICAgIC8vIExpc3Qgb2YgYWxsIHR5cGUgZGVmaW5pdGlvbnMgdGhhdCBuZWVkIHRvIHBhY2thZ2VkIGludG8gdGhlIG5nX3BhY2thZ2UuXG4gICAgdHlwZURlZmluaXRpb25zQXJnLFxuXG4gICAgLy8gTGlzdCBvZiBzaWRlLWVmZmVjdGZ1bCBlbnRyeS1wb2ludHNcbiAgICBzaWRlRWZmZWN0RW50cnlQb2ludHNBcmcsXG4gIF0gPSBwYXJhbXM7XG5cbiAgY29uc3QgZXNtMjAyMiA9IEpTT04ucGFyc2UoZXNtMjAyMkFyZykgYXMgQmF6ZWxGaWxlSW5mb1tdO1xuICBjb25zdCB0eXBlRGVmaW5pdGlvbnMgPSBKU09OLnBhcnNlKHR5cGVEZWZpbml0aW9uc0FyZykgYXMgQmF6ZWxGaWxlSW5mb1tdO1xuICBjb25zdCBzdGF0aWNGaWxlcyA9IEpTT04ucGFyc2Uoc3RhdGljRmlsZXNBcmcpIGFzIEJhemVsRmlsZUluZm9bXTtcbiAgY29uc3QgbWV0YWRhdGEgPSBKU09OLnBhcnNlKG1ldGFkYXRhQXJnKSBhcyBQYWNrYWdlTWV0YWRhdGE7XG4gIGNvbnN0IHNpZGVFZmZlY3RFbnRyeVBvaW50cyA9IEpTT04ucGFyc2Uoc2lkZUVmZmVjdEVudHJ5UG9pbnRzQXJnKSBhcyBzdHJpbmdbXTtcblxuICBpZiAocmVhZG1lTWQpIHtcbiAgICBjb3B5RmlsZShyZWFkbWVNZCwgJ1JFQURNRS5tZCcpO1xuICB9XG5cbiAgaWYgKGxpY2Vuc2VGaWxlKSB7XG4gICAgY29weUZpbGUobGljZW5zZUZpbGUsICdMSUNFTlNFJyk7XG4gIH1cblxuICAvKipcbiAgICogV3JpdGVzIGEgZmlsZSB3aXRoIHRoZSBzcGVjaWZpZWQgY29udGVudCBpbnRvIHRoZSBwYWNrYWdlIG91dHB1dC5cbiAgICogQHBhcmFtIG91dHB1dFJlbGF0aXZlUGF0aCBSZWxhdGl2ZSBwYXRoIGluIHRoZSBvdXRwdXQgZGlyZWN0b3J5IHdoZXJlIHRoZVxuICAgKiAgIGZpbGUgaXMgd3JpdHRlbiB0by5cbiAgICogQHBhcmFtIGZpbGVDb250ZW50IENvbnRlbnQgb2YgdGhlIGZpbGUuXG4gICAqL1xuICBmdW5jdGlvbiB3cml0ZUZpbGUob3V0cHV0UmVsYXRpdmVQYXRoOiBzdHJpbmcsIGZpbGVDb250ZW50OiBzdHJpbmcgfCBCdWZmZXIpIHtcbiAgICBjb25zdCBvdXRwdXRQYXRoID0gcGF0aC5qb2luKG91dHB1dERpckV4ZWNQYXRoLCBvdXRwdXRSZWxhdGl2ZVBhdGgpO1xuXG4gICAgLy8gQWx3YXlzIGVuc3VyZSB0aGF0IHRoZSB0YXJnZXQgZGlyZWN0b3J5IGV4aXN0cy5cbiAgICBmcy5ta2RpclN5bmMocGF0aC5kaXJuYW1lKG91dHB1dFBhdGgpLCB7cmVjdXJzaXZlOiB0cnVlfSk7XG4gICAgZnMud3JpdGVGaWxlU3luYyhvdXRwdXRQYXRoLCBmaWxlQ29udGVudCk7XG4gIH1cblxuICAvKipcbiAgICogQ29waWVzIGEgZmlsZSBpbnRvIHRoZSBwYWNrYWdlIG91dHB1dCB0byB0aGUgc3BlY2lmaWVkIGxvY2F0aW9uLlxuICAgKiBAcGFyYW0gaW5wdXRQYXRoIEZpbGUgdGhhdCBzaG91bGQgYmUgY29waWVkLlxuICAgKiBAcGFyYW0gb3V0cHV0UmVsYXRpdmVQYXRoIFJlbGF0aXZlIHBhdGggaW4gdGhlIG91dHB1dCBkaXJlY3Rvcnkgd2hlcmUgdGhlXG4gICAqICAgZmlsZSBpcyB3cml0dGVuIHRvLlxuICAgKiBAcGFyYW0gdHJhbnNmb3JtIE9wdGlvbmFsIHRleHQgY29udGVudCB0cmFuc2Zvcm0uXG4gICAqL1xuICBmdW5jdGlvbiBjb3B5RmlsZShcbiAgICBpbnB1dFBhdGg6IHN0cmluZyxcbiAgICBvdXRwdXRSZWxhdGl2ZVBhdGg6IHN0cmluZyxcbiAgICB0cmFuc2Zvcm06ICh0ZXh0OiBzdHJpbmcpID0+IHN0cmluZyA9ICh0KSA9PiB0LFxuICApIHtcbiAgICBjb25zdCBmaWxlQ29udGVudCA9IGZzLnJlYWRGaWxlU3luYyhpbnB1dFBhdGgsICd1dGY4Jyk7XG4gICAgd3JpdGVGaWxlKG91dHB1dFJlbGF0aXZlUGF0aCwgdHJhbnNmb3JtKGZpbGVDb250ZW50KSk7XG4gIH1cblxuICAvKipcbiAgICogR2V0cyB0aGUgcmVsYXRpdmUgcGF0aCBmb3IgdGhlIGdpdmVuIGZpbGUgd2l0aGluIHRoZSBvd25pbmcgcGFja2FnZS4gVGhpc1xuICAgKiBhc3N1bWVzIHRoZSBmaWxlIGlzIGNvbnRhaW5lZCBpbiB0aGUgb3duaW5nIHBhY2thZ2UuXG4gICAqXG4gICAqIGUuZy4gY29uc2lkZXIgdGhlIG93bmluZyBwYWNrYWdlIGlzIGBwYWNrYWdlcy9jb3JlYCBhbmQgdGhlIGlucHV0IGZpbGVcbiAgICogaXMgYHBhY2thZ2VzL2NvcmUvdGVzdGluZy9pbmRleC5kLnRzYC4gVGhpcyBmdW5jdGlvbiB3b3VsZCByZXR1cm4gdGhlXG4gICAqIHJlbGF0aXZlIHBhdGggYXMgZm9sbG93ZWQ6IGB0ZXN0aW5nL2luZGV4LmQudHNgLlxuICAgKi9cbiAgZnVuY3Rpb24gZ2V0T3duaW5nUGFja2FnZVJlbGF0aXZlUGF0aChmaWxlOiBCYXplbEZpbGVJbmZvKTogc3RyaW5nIHtcbiAgICByZXR1cm4gcGF0aC5yZWxhdGl2ZShvd25pbmdQYWNrYWdlTmFtZSwgZmlsZS5zaG9ydFBhdGgpO1xuICB9XG5cbiAgLyoqIEdldHMgdGhlIG91dHB1dC1yZWxhdGl2ZSBwYXRoIHdoZXJlIHRoZSB0eXBpbmcgZmlsZSBpcyBiZWluZyB3cml0dGVuIHRvLiAqL1xuICBmdW5jdGlvbiBnZXRUeXBpbmdPdXRwdXRSZWxhdGl2ZVBhdGgoZmlsZTogQmF6ZWxGaWxlSW5mbykge1xuICAgIC8vIFR5cGUgZGVmaW5pdGlvbnMgYXJlIGludGVuZGVkIHRvIGJlIGNvcGllZCBpbnRvIHRoZSBwYWNrYWdlIG91dHB1dCB3aGlsZSBwcmVzZXJ2aW5nIHRoZVxuICAgIC8vIHN1Yi1wYXRoIGZyb20gdGhlIG93bmluZyBwYWNrYWdlLiBlLmcuIGEgZmlsZSBsaWtlIGBwYWNrYWdlcy9hbmltYXRpb25zL2Jyb3dzZXIvX19pbmRleC5kLnRzYFxuICAgIC8vIHdpbGwgZW5kIHVwIGJlaW5nIHdyaXR0ZW4gdG8gYDxwa2ctb3V0Pi9icm93c2VyL2luZGV4LmQudHNgLiBOb3RlIHRoYXQgdHlwZXMgYXJlIGJ1bmRsZWRcbiAgICAvLyBhcyBhIHNlcGFyYXRlIGFjdGlvbiBpbiB0aGUgYG5nX3BhY2thZ2VgIFN0YXJsYXJrIHJ1bGUgYW5kIHByZWZpeGVkIHdpdGggYF9fYCB0byBhdm9pZFxuICAgIC8vIGNvbmZsaWN0cyB3aXRoIHNvdXJjZSBgaW5kZXguZC50c2AgZmlsZXMuIFdlIHJlbW92ZSB0aGlzIHByZWZpeCBoZXJlLlxuICAgIHJldHVybiBnZXRPd25pbmdQYWNrYWdlUmVsYXRpdmVQYXRoKGZpbGUpLnJlcGxhY2UoL19faW5kZXhcXC5kXFwudHMkLywgJ2luZGV4LmQudHMnKTtcbiAgfVxuXG4gIC8qKlxuICAgKiBHZXRzIHRoZSBlbnRyeS1wb2ludCBzdWItcGF0aCBmcm9tIHRoZSBwYWNrYWdlIHJvb3QuIGUuZy4gaWYgdGhlIHBhY2thZ2UgbmFtZVxuICAgKiBpcyBgQGFuZ3VsYXIvY2RrYCwgdGhlbiBmb3IgYEBhbmd1bGFyL2Nkay9hMTF5YCBqdXN0IGBhMTF5YCB3b3VsZCBiZSByZXR1cm5lZC5cbiAgICovXG4gIGZ1bmN0aW9uIGdldEVudHJ5UG9pbnRTdWJwYXRoKG1vZHVsZU5hbWU6IHN0cmluZyk6IHN0cmluZyB7XG4gICAgcmV0dXJuIG1vZHVsZU5hbWUuc2xpY2UoYCR7bWV0YWRhdGEubnBtUGFja2FnZU5hbWV9L2AubGVuZ3RoKTtcbiAgfVxuXG4gIC8qKlxuICAgKiBHZXRzIHdoZXRoZXIgdGhlIGdpdmVuIG1vZHVsZSBuYW1lIHJlc29sdmVzIHRvIGEgc2Vjb25kYXJ5IGVudHJ5LXBvaW50LlxuICAgKiBlLmcuIGlmIHRoZSBwYWNrYWdlIG5hbWUgaXMgYEBhbmd1bGFyL2Nka2AsIHRoZW4gZm9yIGBAYW5ndWxhci9jZGsvYTExeWBcbiAgICogdGhpcyB3b3VsZCByZXR1cm4gYHRydWVgLlxuICAgKi9cbiAgZnVuY3Rpb24gaXNTZWNvbmRhcnlFbnRyeVBvaW50KG1vZHVsZU5hbWU6IHN0cmluZyk6IGJvb2xlYW4ge1xuICAgIHJldHVybiBnZXRFbnRyeVBvaW50U3VicGF0aChtb2R1bGVOYW1lKSAhPT0gJyc7XG4gIH1cblxuICBjb25zdCBjcm9zc0VudHJ5UG9pbnRGYWlsdXJlcyA9IGVzbTIwMjIuZmxhdE1hcCgoZmlsZSkgPT5cbiAgICBhbmFseXplRmlsZUFuZEVuc3VyZU5vQ3Jvc3NJbXBvcnRzKGZpbGUsIG1ldGFkYXRhKSxcbiAgKTtcblxuICBpZiAoY3Jvc3NFbnRyeVBvaW50RmFpbHVyZXMubGVuZ3RoKSB7XG4gICAgY29uc29sZS5lcnJvcihjcm9zc0VudHJ5UG9pbnRGYWlsdXJlcyk7XG4gICAgcHJvY2Vzcy5leGl0KDEpO1xuICB9XG5cbiAgY29uc3QgZmVzbUZpbGVzID0gZ2xvYlN5bmMoJyoqLyonLCB7Y3dkOiBtZXRhZGF0YS5idW5kbGVzT3V0LnBhdGh9KTtcbiAgLy8gQ29weSBhbGwgRkVTTSBmaWxlcyAoYW5kIHRoZWlyIHBvdGVudGlhbCBzaGFyZWQgY2h1bmtzKSBpbnRvIHRoZSBwYWNrYWdlIG91dHB1dC5cbiAgZmVzbUZpbGVzLmZvckVhY2goKGYpID0+IGNvcHlGaWxlKHBhdGguam9pbihtZXRhZGF0YS5idW5kbGVzT3V0LnBhdGgsIGYpLCBmKSk7XG5cbiAgLy8gQ29weSBhbGwgdHlwZSBkZWZpbml0aW9ucyBpbnRvIHRoZSBwYWNrYWdlLCBwcmVzZXJ2aW5nIHRoZSBzdWItcGF0aCBmcm9tIHRoZVxuICAvLyBvd25pbmcgcGFja2FnZS4gZS5nLiBhIGZpbGUgbGlrZSBgcGFja2FnZXMvYW5pbWF0aW9ucy9icm93c2VyL19faW5kZXguZC50c2Agd2lsbFxuICAvLyBlbmQgdXAgaW4gYGJyb3dzZXIvaW5kZXguZC50c2BcbiAgdHlwZURlZmluaXRpb25zLmZvckVhY2goKGYpID0+XG4gICAgY29weUZpbGUoZi5wYXRoLCBnZXRUeXBpbmdPdXRwdXRSZWxhdGl2ZVBhdGgoZiksIHRyYW5zZm9ybVJlbW92ZUFtZE1vZHVsZXMpLFxuICApO1xuXG4gIGZvciAoY29uc3QgZmlsZSBvZiBzdGF0aWNGaWxlcykge1xuICAgIC8vIFdlIGNvcHkgYWxsIGZpbGVzIGludG8gdGhlIHBhY2thZ2Ugb3V0cHV0IHdoaWxlIHByZXNlcnZpbmcgdGhlIHN1Yi1wYXRoIGZyb21cbiAgICAvLyB0aGUgb3duaW5nIHBhY2thZ2UuIGUuZy4gYHBhY2thZ2VzL2NvcmUvcGFja2FnZS5qc29uYCBlbmRzIHVwIGA8cGtnLW91dD4vcGFja2FnZS5qc29uYC5cbiAgICBjb25zdCBvdXRwdXRSZWxhdGl2ZVBhdGggPSBnZXRPd25pbmdQYWNrYWdlUmVsYXRpdmVQYXRoKGZpbGUpO1xuICAgIGxldCBjb250ZW50ID0gZnMucmVhZEZpbGVTeW5jKGZpbGUucGF0aCwgJ3V0ZjgnKTtcblxuICAgIC8vIENoZWNrIGFuZCBtb2RpZnkgcGFja2FnZS5qc29uIGZpbGVzIGFzIG5lY2Vzc2FyeSBmb3IgcHVibGlzaGluZ1xuICAgIGlmIChwYXRoLmJhc2VuYW1lKGZpbGUucGF0aCkgPT09ICdwYWNrYWdlLmpzb24nKSB7XG4gICAgICBjb25zdCBpc1ByaW1hcnlQYWNrYWdlSnNvbiA9IG91dHB1dFJlbGF0aXZlUGF0aCA9PT0gJ3BhY2thZ2UuanNvbic7XG4gICAgICBjb25zdCBwYWNrYWdlSnNvbiA9IEpTT04ucGFyc2UoY29udGVudCkgYXMgUGFja2FnZUpzb247XG4gICAgICBjb25zdCBwYWNrYWdlTmFtZSA9IHBhY2thZ2VKc29uWyduYW1lJ107XG5cbiAgICAgIC8vIFByZXZlbnQgbm9uLXByaW1hcnkgYHBhY2thZ2UuanNvbmAgZmlsZXMgd2hpY2ggd291bGQgdGhyb3ctb2ZmIHJlc29sdXRpb24uXG4gICAgICAvLyBSZXNvbHV0aW9uIGluIHRoZSBwYWNrYWdlIHNob3VsZCBvbmx5IGJlIGJhc2VkIG9uIHRoZSB0b3AtbGV2ZWwgYHBhY2thZ2UuanNvbmAuXG4gICAgICBpZiAoIWlzUHJpbWFyeVBhY2thZ2VKc29uKSB7XG4gICAgICAgIHRocm93IEVycm9yKFxuICAgICAgICAgIGBGb3VuZCBhIG5lc3RlZCBcInBhY2thZ2UuanNvblwiIGZpbGUgaW4gdGhlIHBhY2thZ2Ugb3V0cHV0OiAke2ZpbGUuc2hvcnRQYXRofS5cXG5gICtcbiAgICAgICAgICAgIGBBbGwgaW5mb3JtYXRpb24gb2YgdGhlIHBhY2thZ2Ugc2hvdWxkIHJlc2lkZSBpbiB0aGUgcHJpbWFyeSBwYWNrYWdlIGZpbGUuYCxcbiAgICAgICAgKTtcbiAgICAgIH1cblxuICAgICAgLy8gQ2hlY2sgaWYgdGhlIGBuYW1lYCBmaWVsZCBvZiB0aGUgYHBhY2thZ2UuanNvbmAgZmlsZXMgYXJlIG1hdGNoaW5nIHdpdGhcbiAgICAgIC8vIG5hbWUgb2YgdGhlIE5QTSBwYWNrYWdlLiBUaGlzIGlzIGFuIGFkZGl0aW9uYWwgc2FmZXR5IGNoZWNrLlxuICAgICAgaWYgKHBhY2thZ2VOYW1lICE9PSBtZXRhZGF0YS5ucG1QYWNrYWdlTmFtZSkge1xuICAgICAgICB0aHJvdyBFcnJvcihcbiAgICAgICAgICBgUHJpbWFyeSBcInBhY2thZ2UuanNvblwiIGhhcyBtaXNtYXRjaGluZyBwYWNrYWdlIG5hbWUuIEV4cGVjdGVkIHRoZSBgICtcbiAgICAgICAgICAgIGBwYWNrYWdlIHRvIGJlIG5hbWVkIFwiJHttZXRhZGF0YS5ucG1QYWNrYWdlTmFtZX1cIiwgYnV0IGlzIHNldCB0bzogJHtwYWNrYWdlTmFtZX0uYCxcbiAgICAgICAgKTtcbiAgICAgIH1cblxuICAgICAgbGV0IG5ld1BhY2thZ2VKc29uID0gaW5zZXJ0Rm9ybWF0RmllbGRzSW50b1BhY2thZ2VKc29uKFxuICAgICAgICBvdXRwdXRSZWxhdGl2ZVBhdGgsXG4gICAgICAgIHBhY2thZ2VKc29uLFxuICAgICAgICBmYWxzZSxcbiAgICAgICk7XG5cbiAgICAgIG5ld1BhY2thZ2VKc29uID0gdXBkYXRlUHJpbWFyeVBhY2thZ2VKc29uKG5ld1BhY2thZ2VKc29uKTtcblxuICAgICAgLy8gVXBkYXRlIHRoZSBjb250ZW50IHdpdGggdGhlIG5ldyBgcGFja2FnZS5qc29uYCBmaWxlIGNvbnRlbnQuXG4gICAgICBjb250ZW50ID0gSlNPTi5zdHJpbmdpZnkobmV3UGFja2FnZUpzb24sIG51bGwsIDIpO1xuICAgIH1cblxuICAgIHdyaXRlRmlsZShvdXRwdXRSZWxhdGl2ZVBhdGgsIGNvbnRlbnQpO1xuICB9XG5cbiAgLyoqXG4gICAqIEluc2VydHMgb3IgZWRpdHMgcHJvcGVydGllcyBpbnRvIHRoZSBwYWNrYWdlLmpzb24gZmlsZShzKSBpbiB0aGUgcGFja2FnZSBzbyB0aGF0XG4gICAqIHRoZXkgcG9pbnQgdG8gYWxsIHRoZSByaWdodCBnZW5lcmF0ZWQgYXJ0aWZhY3RzLlxuICAgKlxuICAgKiBAcGFyYW0gcGFja2FnZUpzb25PdXRSZWxhdGl2ZVBhdGggUGF0aCB3aGVyZSB0aGUgYHBhY2thZ2UuanNvbmAgaXMgc3RvcmVkIGluXG4gICAqICAgdGhlIHBhY2thZ2Ugb3V0cHV0LlxuICAgKiBAcGFyYW0gcGFyc2VkUGFja2FnZSBQYXJzZWQgcGFja2FnZS5qc29uIGNvbnRlbnRcbiAgICogQHBhcmFtIGlzR2VuZXJhdGVkUGFja2FnZUpzb24gV2hldGhlciB0aGUgcGFzc2VkIHBhY2thZ2UuanNvbiBoYXMgYmVlbiBnZW5lcmF0ZWQuXG4gICAqL1xuICBmdW5jdGlvbiBpbnNlcnRGb3JtYXRGaWVsZHNJbnRvUGFja2FnZUpzb24oXG4gICAgcGFja2FnZUpzb25PdXRSZWxhdGl2ZVBhdGg6IHN0cmluZyxcbiAgICBwYXJzZWRQYWNrYWdlOiBSZWFkb25seTxQYWNrYWdlSnNvbj4sXG4gICAgaXNHZW5lcmF0ZWRQYWNrYWdlSnNvbjogYm9vbGVhbixcbiAgKTogUGFja2FnZUpzb24ge1xuICAgIGNvbnN0IHBhY2thZ2VKc29uOiBQYWNrYWdlSnNvbiA9IHsuLi5wYXJzZWRQYWNrYWdlfTtcbiAgICBjb25zdCBwYWNrYWdlTmFtZSA9IHBhY2thZ2VKc29uWyduYW1lJ107XG4gICAgY29uc3QgZW50cnlQb2ludEluZm8gPSBtZXRhZGF0YS5lbnRyeVBvaW50c1twYWNrYWdlTmFtZV07XG4gICAgY29uc3QgcGFja2FnZUpzb25Db250YWluaW5nRGlyID0gcGF0aC5kaXJuYW1lKHBhY2thZ2VKc29uT3V0UmVsYXRpdmVQYXRoKTtcblxuICAgIC8vIElmIGEgcGFja2FnZSBqc29uIGZpbGUgaGFzIGJlZW4gZGlzY292ZXJlZCB0aGF0IGRvZXMgbm90IG1hdGNoIGFueVxuICAgIC8vIGVudHJ5LXBvaW50IGluIHRoZSBtZXRhZGF0YSwgd2UgcmVwb3J0IGEgd2FybmluZyBhcyBtb3N0IGxpa2VseSB0aGUgdGFyZ2V0XG4gICAgLy8gaXMgY29uZmlndXJlZCBpbmNvcnJlY3RseSAoZS5nLiBtaXNzaW5nIGBtb2R1bGVfbmFtZWAgYXR0cmlidXRlKS5cbiAgICBpZiAoIWVudHJ5UG9pbnRJbmZvKSB7XG4gICAgICAvLyBJZGVhbGx5IHdlIHNob3VsZCB0aHJvdyBoZXJlLCBhcyB3ZSBnb3QgYW4gZW50cnkgcG9pbnQgdGhhdCBkb2Vzbid0XG4gICAgICAvLyBoYXZlIGZsYXQgbW9kdWxlIG1ldGFkYXRhIC8gYnVuZGxlIGluZGV4LCBzbyBpdCBtYXkgaGF2ZSBiZWVuIGFuXG4gICAgICAvLyBuZ19tb2R1bGUgdGhhdCdzIG1pc3NpbmcgYSBtb2R1bGVfbmFtZSBhdHRyaWJ1dGUuXG4gICAgICAvLyBIb3dldmVyLCBAYW5ndWxhci9jb21waWxlciBjYW4ndCBiZSBhbiBuZ19tb2R1bGUsIGFzIGl0J3MgdGhlIGludGVybmFsc1xuICAgICAgLy8gb2YgdGhlIG5nYyBjb21waWxlciwgeWV0IHdlIHdhbnQgdG8gYnVpbGQgYW4gbmdfcGFja2FnZSBmb3IgaXQuXG4gICAgICAvLyBTbyBpZ25vcmUgcGFja2FnZS5qc29uIGZpbGVzIHdoZW4gd2UgYXJlIG1pc3NpbmcgZGF0YS5cbiAgICAgIGNvbnNvbGUuZXJyb3IoJ1dBUk5JTkc6IG5vIG1vZHVsZSBtZXRhZGF0YSBmb3IgcGFja2FnZScsIHBhY2thZ2VOYW1lKTtcbiAgICAgIGNvbnNvbGUuZXJyb3IoJyAgIE5vdCB1cGRhdGluZyB0aGUgcGFja2FnZS5qc29uIGZpbGUgdG8gcG9pbnQgdG8gaXQnKTtcbiAgICAgIGNvbnNvbGUuZXJyb3IoXG4gICAgICAgICcgICBUaGUgbmdfbW9kdWxlIGZvciB0aGlzIHBhY2thZ2UgaXMgcG9zc2libHkgbWlzc2luZyB0aGUgbW9kdWxlX25hbWUgYXR0cmlidXRlICcsXG4gICAgICApO1xuICAgICAgcmV0dXJuIHBhY2thZ2VKc29uO1xuICAgIH1cblxuICAgIC8vIElmIHdlIGd1ZXNzZWQgdGhlIGluZGV4IHBhdGhzIGZvciBhIG1vZHVsZSwgYW5kIGl0IGNvbnRhaW5zIGFuIGV4cGxpY2l0IGBwYWNrYWdlLmpzb25gXG4gICAgLy8gZmlsZSB0aGF0IGFscmVhZHkgc2V0cyBmb3JtYXQgcHJvcGVydGllcywgd2Ugc2tpcCBhdXRvbWF0aWMgaW5zZXJ0aW9uIG9mIGZvcm1hdFxuICAgIC8vIHByb3BlcnRpZXMgYnV0IHJlcG9ydCBhIHdhcm5pbmcgaW4gY2FzZSBwcm9wZXJ0aWVzIGhhdmUgYmVlbiBzZXQgYnkgYWNjaWRlbnQuXG4gICAgaWYgKFxuICAgICAgZW50cnlQb2ludEluZm8uZ3Vlc3NlZFBhdGhzICYmXG4gICAgICAhaXNHZW5lcmF0ZWRQYWNrYWdlSnNvbiAmJlxuICAgICAgaGFzRXhwbGljaXRGb3JtYXRQcm9wZXJ0aWVzKHBhY2thZ2VKc29uKVxuICAgICkge1xuICAgICAgY29uc29sZS5lcnJvcignV0FSTklORzogYHBhY2thZ2UuanNvbmAgZXhwbGljaXRseSBzZXRzIGZvcm1hdCBwcm9wZXJ0aWVzIChsaWtlIGBtYWluYCkuJyk7XG4gICAgICBjb25zb2xlLmVycm9yKFxuICAgICAgICAnICAgIFNraXBwaW5nIGF1dG9tYXRpYyBpbnNlcnRpb24gb2YgZm9ybWF0IHByb3BlcnRpZXMgYXMgZXhwbGljaXQgJyArXG4gICAgICAgICAgJ2Zvcm1hdCBwcm9wZXJ0aWVzIGFyZSBzZXQuJyxcbiAgICAgICk7XG4gICAgICBjb25zb2xlLmVycm9yKCcgICAgSWdub3JlIHRoaXMgd2FybmluZyBpZiBleHBsaWNpdCBwcm9wZXJ0aWVzIGFyZSBzZXQgaW50ZW50aW9uYWxseS4nKTtcbiAgICAgIHJldHVybiBwYWNrYWdlSnNvbjtcbiAgICB9XG5cbiAgICBjb25zdCBmZXNtMjAyMlJlbGF0aXZlT3V0UGF0aCA9IGVudHJ5UG9pbnRJbmZvLmZlc20yMDIyUmVsYXRpdmVQYXRoO1xuICAgIGNvbnN0IHR5cGluZ3NSZWxhdGl2ZU91dFBhdGggPSBnZXRUeXBpbmdPdXRwdXRSZWxhdGl2ZVBhdGgoZW50cnlQb2ludEluZm8udHlwaW5nc0VudHJ5UG9pbnQpO1xuXG4gICAgcGFja2FnZUpzb24ubW9kdWxlID0gbm9ybWFsaXplUGF0aChcbiAgICAgIHBhdGgucmVsYXRpdmUocGFja2FnZUpzb25Db250YWluaW5nRGlyLCBmZXNtMjAyMlJlbGF0aXZlT3V0UGF0aCksXG4gICAgKTtcbiAgICBwYWNrYWdlSnNvbi50eXBpbmdzID0gbm9ybWFsaXplUGF0aChcbiAgICAgIHBhdGgucmVsYXRpdmUocGFja2FnZUpzb25Db250YWluaW5nRGlyLCB0eXBpbmdzUmVsYXRpdmVPdXRQYXRoKSxcbiAgICApO1xuXG4gICAgcmV0dXJuIHBhY2thZ2VKc29uO1xuICB9XG5cbiAgLyoqXG4gICAqIFVwZGF0ZXMgdGhlIHByaW1hcnkgYHBhY2thZ2UuanNvbmAgZmlsZSBvZiB0aGUgTlBNIHBhY2thZ2UgdG8gc3BlY2lmeVxuICAgKiB0aGUgbW9kdWxlIGNvbmRpdGlvbmFsIGV4cG9ydHMgYW5kIHRoZSBFU00gbW9kdWxlIHR5cGUuXG4gICAqL1xuICBmdW5jdGlvbiB1cGRhdGVQcmltYXJ5UGFja2FnZUpzb24ocGFja2FnZUpzb246IFJlYWRvbmx5PFBhY2thZ2VKc29uPik6IFBhY2thZ2VKc29uIHtcbiAgICBpZiAocGFja2FnZUpzb24udHlwZSAhPT0gdW5kZWZpbmVkICYmIHBhY2thZ2VKc29uLnR5cGUgIT09ICdtb2R1bGUnKSB7XG4gICAgICB0aHJvdyBFcnJvcihcbiAgICAgICAgJ1RoZSBwcmltYXJ5IFwicGFja2FnZS5qc29uXCIgZmlsZSBvZiB0aGUgcGFja2FnZSBzZXRzIHRoZSBcInR5cGVcIiBmaWVsZCAnICtcbiAgICAgICAgICAndGhhdCBpcyBjb250cm9sbGVkIGJ5IHRoZSBwYWNrYWdlci4gUGxlYXNlIHVuc2V0IGl0IG9yIHNldCBgdHlwZWAgdG8gYG1vZHVsZWAuJyxcbiAgICAgICk7XG4gICAgfVxuXG4gICAgY29uc3QgbmV3UGFja2FnZUpzb246IFBhY2thZ2VKc29uID0gey4uLnBhY2thZ2VKc29ufTtcblxuICAgIG5ld1BhY2thZ2VKc29uLnR5cGUgPSAnbW9kdWxlJztcblxuICAgIC8vIFRoZSBgcGFja2FnZS5qc29uYCBmaWxlIGlzIG1hZGUgcHVibGljbHkgYWNjZXNzaWJsZSBmb3IgdG9vbHMgdGhhdFxuICAgIC8vIG1pZ2h0IHdhbnQgdG8gcXVlcnkgaW5mb3JtYXRpb24gZnJvbSB0aGUgQW5ndWxhciBOUE0gcGFja2FnZS5cbiAgICBpbnNlcnRFeHBvcnRNYXBwaW5nT3JFcnJvcihuZXdQYWNrYWdlSnNvbiwgJy4vcGFja2FnZS5qc29uJywge2RlZmF1bHQ6ICcuL3BhY2thZ2UuanNvbid9KTtcblxuICAgIC8vIENhcHR1cmUgYWxsIGVudHJ5LXBvaW50cyBpbiB0aGUgYGV4cG9ydHNgIGZpZWxkIHVzaW5nIHRoZSBzdWJwYXRoIGV4cG9ydCBkZWNsYXJhdGlvbnM6XG4gICAgLy8gaHR0cHM6Ly9ub2RlanMub3JnL2FwaS9wYWNrYWdlcy5odG1sI3BhY2thZ2VzX3N1YnBhdGhfZXhwb3J0cy5cbiAgICBmb3IgKGNvbnN0IFttb2R1bGVOYW1lLCBlbnRyeVBvaW50XSBvZiBPYmplY3QuZW50cmllcyhtZXRhZGF0YS5lbnRyeVBvaW50cykpIHtcbiAgICAgIGNvbnN0IHN1YnBhdGggPSBpc1NlY29uZGFyeUVudHJ5UG9pbnQobW9kdWxlTmFtZSlcbiAgICAgICAgPyBgLi8ke2dldEVudHJ5UG9pbnRTdWJwYXRoKG1vZHVsZU5hbWUpfWBcbiAgICAgICAgOiAnLic7XG4gICAgICBjb25zdCBmZXNtMjAyMk91dFJlbGF0aXZlUGF0aCA9IGVudHJ5UG9pbnQuZmVzbTIwMjJSZWxhdGl2ZVBhdGg7XG4gICAgICBjb25zdCB0eXBlc091dFJlbGF0aXZlUGF0aCA9IGdldFR5cGluZ091dHB1dFJlbGF0aXZlUGF0aChlbnRyeVBvaW50LnR5cGluZ3NFbnRyeVBvaW50KTtcblxuICAgICAgLy8gSW5zZXJ0IHRoZSBleHBvcnQgbWFwcGluZyBmb3IgdGhlIGVudHJ5LXBvaW50LiBXZSBzZXQgYGRlZmF1bHRgIHRvIHRoZSBGRVNNIDIwMjJcbiAgICAgIC8vIG91dHB1dCwgYW5kIGFsc28gc2V0IHRoZSBgdHlwZXNgIGNvbmRpdGlvbiB3aGljaCB3aWxsIGJlIHJlc3BlY3RlZCBieSBUUyA0LjUuXG4gICAgICAvLyBodHRwczovL2dpdGh1Yi5jb20vbWljcm9zb2Z0L1R5cGVTY3JpcHQvcHVsbC80NTg4NC5cbiAgICAgIGluc2VydEV4cG9ydE1hcHBpbmdPckVycm9yKG5ld1BhY2thZ2VKc29uLCBzdWJwYXRoLCB7XG4gICAgICAgIHR5cGVzOiBub3JtYWxpemVQYXRoKHR5cGVzT3V0UmVsYXRpdmVQYXRoKSxcbiAgICAgICAgLy8gTm90ZTogVGhlIGRlZmF1bHQgY29uZGl0aW9ucyBuZWVkcyB0byBiZSB0aGUgbGFzdCBvbmUuXG4gICAgICAgIGRlZmF1bHQ6IG5vcm1hbGl6ZVBhdGgoZmVzbTIwMjJPdXRSZWxhdGl2ZVBhdGgpLFxuICAgICAgfSk7XG4gICAgfVxuXG4gICAgY2hlY2tQYWNrYWdlSnNvblNpZGVFZmZlY3RzKHBhY2thZ2VKc29uKTtcblxuICAgIHJldHVybiBuZXdQYWNrYWdlSnNvbjtcbiAgfVxuXG4gIGZ1bmN0aW9uIGNoZWNrUGFja2FnZUpzb25TaWRlRWZmZWN0cyhwYWNrYWdlSnNvbjogUGFja2FnZUpzb24pOiB2b2lkIHtcbiAgICAvLyBDb252ZW5pZW5jZSBpZiB0aGVyZSBhcmUgbm8gc2lkZSBlZmZlY3RzLCBhbmQgaXQncyBleHBsaWNpdGx5IG1hcmtlZC5cbiAgICAvLyBUaGlzIGlzIG9rYXkgYW5kIHdlIGRvbid0IGFzayB0aGUgZGV2ZWxvcGVyIHRvIGRyb3AgdGhlIGV4cGxpY2l0IGZpZWxkLlxuICAgIGlmIChwYWNrYWdlSnNvbi5zaWRlRWZmZWN0cyA9PT0gZmFsc2UgJiYgc2lkZUVmZmVjdEVudHJ5UG9pbnRzLmxlbmd0aCA9PT0gMCkge1xuICAgICAgcmV0dXJuO1xuICAgIH1cblxuICAgIGlmIChwYWNrYWdlSnNvbi5zaWRlRWZmZWN0cyA9PT0gdHJ1ZSkge1xuICAgICAgdGhyb3cgRXJyb3IoXG4gICAgICAgICdVbmV4cGVjdGVkIGBzaWRlRWZmZWN0c2AgZmllbGQgaW4gYHBhY2thZ2UuanNvbmAuICcgK1xuICAgICAgICAgICdTaWRlIGVmZmVjdHMgc2hvdWxkIGJlIGZpbmUtZ3JhaW5lZCBhbmQgbWFya2VkIHZpYSB0aGUgQmF6ZWwgYHNpZGVfZWZmZWN0X2VudHJ5X3BvaW50c2Agb3B0aW9uLicsXG4gICAgICApO1xuICAgIH1cblxuICAgIGNvbnN0IHNpZGVFZmZlY3RzID0gcGFja2FnZUpzb24uc2lkZUVmZmVjdHMgYXMgdW5kZWZpbmVkIHwgZmFsc2UgfCBzdHJpbmdbXTtcbiAgICBjb25zdCBuZWVkZWRTaWRlRWZmZWN0cyA9IHNpZGVFZmZlY3RFbnRyeVBvaW50cy5tYXAoXG4gICAgICAoZW50cnlQb2ludE1vZHVsZSkgPT4gYC4vJHttZXRhZGF0YS5lbnRyeVBvaW50c1tlbnRyeVBvaW50TW9kdWxlXS5mZXNtMjAyMlJlbGF0aXZlUGF0aH1gLFxuICAgICk7XG4gICAgY29uc3QgbWlzc2luZ1NpZGVFZmZlY3RzID0gbmVlZGVkU2lkZUVmZmVjdHMuZmlsdGVyKFxuICAgICAgKHApID0+XG4gICAgICAgIC8vIEl0J3MgbWlzc2luZywgaWYgdGhlIHdob2xlIHBhY2thZ2UgaXMgbWFya2VkIGFzIGhhdmluZyBubyBzaWRlIGVmZmVjdHMuXG4gICAgICAgIHNpZGVFZmZlY3RzID09PSBmYWxzZSB8fFxuICAgICAgICAvLyBBbHRlcm5hdGl2ZWx5LCBpdCdzIG1pc3NpbmcgaWYgdGhlIGV4cGxpY2l0IGxpc3QgZG9lc24ndCBjb250YWluIHRoZSBwYXR0ZXJuLlxuICAgICAgICAhKHNpZGVFZmZlY3RzID8/IFtdKS5pbmNsdWRlcyhwKSxcbiAgICApO1xuXG4gICAgaWYgKG1pc3NpbmdTaWRlRWZmZWN0cy5sZW5ndGggPiAwKSB7XG4gICAgICB0aHJvdyBFcnJvcihcbiAgICAgICAgJ01pc3Npbmcgc2lkZSBlZmZlY3RzIGluIGBwYWNrYWdlLmpzb25gIGBzaWRlRWZmZWN0c2AgZmllbGQuICcgK1xuICAgICAgICAgICdQbGVhc2UgYWRkIHRoZSBmb2xsb3dpbmcgc2lkZSBlZmZlY3QgZmlsZSBwYXR0ZXJuczpcXG4nICtcbiAgICAgICAgICBtaXNzaW5nU2lkZUVmZmVjdHMuam9pbignXFxuIC0gJyksXG4gICAgICApO1xuICAgIH1cblxuICAgIC8vIEZpbmQgcG90ZW50aWFsIHNpZGUtZWZmZWN0cyB0aGF0IHJlZmVyIHRvIG91ciBGRVNNIGJ1bmRsZXMsIGJ1dCBhcmVuJ3QgcGFydFxuICAgIC8vIG9mIHRoZSBgbmdfcGFja2FnZWAga25vd24gZW50cnkgcG9pbnRzLlxuICAgIGNvbnN0IHVuZXhwZWN0ZWRFeHRyYSA9XG4gICAgICBzaWRlRWZmZWN0cyAhPT0gZmFsc2VcbiAgICAgICAgPyAoc2lkZUVmZmVjdHMgPz8gW10pLmZpbHRlcihcbiAgICAgICAgICAgIChwKSA9PiBwLmluY2x1ZGVzKCdmZXNtMjAyMicpICYmICFuZWVkZWRTaWRlRWZmZWN0cy5pbmNsdWRlcyhwKSxcbiAgICAgICAgICApXG4gICAgICAgIDogW107XG4gICAgaWYgKHVuZXhwZWN0ZWRFeHRyYS5sZW5ndGggPiAwKSB7XG4gICAgICB0aHJvdyBFcnJvcihcbiAgICAgICAgJ1VuZXhwZWN0ZWQgc2lkZSBlZmZlY3RzIGluIGBwYWNrYWdlLmpzb25gIGBzaWRlRWZmZWN0c2AgZmllbGQgdGhhdCBpcyBub3Qga25vd24gdG8gYG5nX3BhY2thZ2VgLiAnICtcbiAgICAgICAgICAnUGxlYXNlIGFkZCB0aGUgc2lkZSBlZmZlY3QgZW50cnkgcG9pbnQgdG8gdGhlIEJhemVsIGBzaWRlX2VmZmVjdF9lbnRyeV9wb2ludHNgIG9wdGlvbi4gJyArXG4gICAgICAgICAgJ1VuZXhwZWN0ZWQgcGF0dGVybnM6XFxuJyArXG4gICAgICAgICAgdW5leHBlY3RlZEV4dHJhLmpvaW4oJ1xcbiAtICcpLFxuICAgICAgKTtcbiAgICB9XG4gIH1cblxuICAvKipcbiAgICogSW5zZXJ0cyBhIHN1YnBhdGggZXhwb3J0IG1hcHBpbmcgaW50byB0aGUgc3BlY2lmaWVkIGBwYWNrYWdlLmpzb25gIG9iamVjdC5cbiAgICogQHRocm93cyBBbiBlcnJvciBpZiB0aGUgbWFwcGluZyBpcyBhbHJlYWR5IGRlZmluZWQgYW5kIHdvdWxkIGNvbmZsaWN0LlxuICAgKi9cbiAgZnVuY3Rpb24gaW5zZXJ0RXhwb3J0TWFwcGluZ09yRXJyb3IoXG4gICAgcGFja2FnZUpzb246IFBhY2thZ2VKc29uLFxuICAgIHN1YnBhdGg6IHN0cmluZyxcbiAgICBtYXBwaW5nOiBDb25kaXRpb25hbEV4cG9ydCxcbiAgKSB7XG4gICAgaWYgKHBhY2thZ2VKc29uLmV4cG9ydHMgPT09IHVuZGVmaW5lZCkge1xuICAgICAgcGFja2FnZUpzb24uZXhwb3J0cyA9IHt9O1xuICAgIH1cbiAgICBpZiAocGFja2FnZUpzb24uZXhwb3J0c1tzdWJwYXRoXSA9PT0gdW5kZWZpbmVkKSB7XG4gICAgICBwYWNrYWdlSnNvbi5leHBvcnRzW3N1YnBhdGhdID0ge307XG4gICAgfVxuXG4gICAgY29uc3Qgc3VicGF0aEV4cG9ydCA9IHBhY2thZ2VKc29uLmV4cG9ydHNbc3VicGF0aF07XG5cbiAgICAvLyBHbyB0aHJvdWdoIGFsbCBjb25kaXRpb25zIHRoYXQgc2hvdWxkIGJlIGluc2VydGVkLiBJZiB0aGUgY29uZGl0aW9uIGlzIGFscmVhZHlcbiAgICAvLyBtYW51YWxseSBzZXQgb2YgdGhlIHN1YnBhdGggZXhwb3J0LCB3ZSB0aHJvdyBhbiBlcnJvci4gSW4gZ2VuZXJhbCwgd2UgYWxsb3cgZm9yXG4gICAgLy8gYWRkaXRpb25hbCBjb25kaXRpb25zIHRvIGJlIHNldC4gVGhlc2Ugd2lsbCBhbHdheXMgcHJlY2VkZSB0aGUgZ2VuZXJhdGVkIG9uZXMuXG4gICAgZm9yIChjb25zdCBjb25kaXRpb25OYW1lIG9mIE9iamVjdC5rZXlzKG1hcHBpbmcpIGFzIFtrZXlvZiBDb25kaXRpb25hbEV4cG9ydF0pIHtcbiAgICAgIGlmIChzdWJwYXRoRXhwb3J0W2NvbmRpdGlvbk5hbWVdICE9PSB1bmRlZmluZWQpIHtcbiAgICAgICAgdGhyb3cgRXJyb3IoXG4gICAgICAgICAgYEZvdW5kIGEgY29uZmxpY3RpbmcgZXhwb3J0IGNvbmRpdGlvbiBmb3IgXCIke3N1YnBhdGh9XCIuIFRoZSBcIiR7Y29uZGl0aW9uTmFtZX1cIiBgICtcbiAgICAgICAgICAgIGBjb25kaXRpb24gd291bGQgYmUgb3ZlcnJpZGRlbiBieSB0aGUgcGFja2FnZXIuIFBsZWFzZSB1bnNldCBpdC5gLFxuICAgICAgICApO1xuICAgICAgfVxuXG4gICAgICAvLyAqKk5vdGUqKjogVGhlIG9yZGVyIG9mIHRoZSBjb25kaXRpb25zIGlzIHByZXNlcnZlZCBldmVuIHRob3VnaCB3ZSBhcmUgc2V0dGluZ1xuICAgICAgLy8gdGhlIGNvbmRpdGlvbnMgb25jZSBhdCBhIHRpbWUgKHRoZSBsYXRlc3QgYXNzaWdubWVudCB3aWxsIGJlIGF0IHRoZSBlbmQpLlxuICAgICAgc3VicGF0aEV4cG9ydFtjb25kaXRpb25OYW1lXSA9IG1hcHBpbmdbY29uZGl0aW9uTmFtZV07XG4gICAgfVxuICB9XG5cbiAgLyoqIFdoZXRoZXIgdGhlIHBhY2thZ2UgZXhwbGljaXRseSBzZXRzIGFueSBvZiB0aGUgZm9ybWF0IHByb3BlcnRpZXMgKGxpa2UgYG1haW5gKS4gKi9cbiAgZnVuY3Rpb24gaGFzRXhwbGljaXRGb3JtYXRQcm9wZXJ0aWVzKHBhcnNlZFBhY2thZ2U6IFJlYWRvbmx5PFBhY2thZ2VKc29uPik6IGJvb2xlYW4ge1xuICAgIHJldHVybiBPYmplY3Qua2V5cyhwYXJzZWRQYWNrYWdlKS5zb21lKChmaWVsZE5hbWU6IHN0cmluZykgPT5cbiAgICAgIGtub3duRm9ybWF0UGFja2FnZUpzb25Gb3JtYXRGaWVsZHMuaW5jbHVkZXMoZmllbGROYW1lIGFzIEtub3duUGFja2FnZUpzb25Gb3JtYXRGaWVsZHMpLFxuICAgICk7XG4gIH1cblxuICAvKipcbiAgICogTm9ybWFsaXplcyB0aGUgc3BlY2lmaWVkIHBhdGggYnkgcmVwbGFjaW5nIGJhY2tzbGFzaCBzZXBhcmF0b3JzIHdpdGggUG9zaXhcbiAgICogZm9yd2FyZCBzbGFzaCBzZXBhcmF0b3JzLlxuICAgKi9cbiAgZnVuY3Rpb24gbm9ybWFsaXplUGF0aChwYXRoOiBzdHJpbmcpOiBzdHJpbmcge1xuICAgIGNvbnN0IHJlc3VsdCA9IHBhdGgucmVwbGFjZSgvXFxcXC9nLCAnLycpO1xuICAgIHJldHVybiByZXN1bHQuc3RhcnRzV2l0aCgnLicpID8gcmVzdWx0IDogYC4vJHtyZXN1bHR9YDtcbiAgfVxuXG4gIC8qKlxuICAgKiBTdHJpcCB0aGUgbmFtZWQgQU1EIG1vZHVsZSBkaXJlY3RpdmUgY29tbWVudHMuXG4gICAqXG4gICAqIFRob3NlIGFyZSBhZGRlZCBieSBCYXplbCBhbmQgYXJlbid0IHJlbGV2YW50IGZvciBvdXIgdXNlcnMuXG4gICAqL1xuICBmdW5jdGlvbiB0cmFuc2Zvcm1SZW1vdmVBbWRNb2R1bGVzKGR0c1RleHQ6IHN0cmluZyk6IHN0cmluZyB7XG4gICAgcmV0dXJuIGR0c1RleHQucmVwbGFjZSgvXlxcL1xcL1xcLyA8YW1kLW1vZHVsZSBuYW1lPS4qXFwvPltcXHJcXG5dKy9nbSwgJycpO1xuICB9XG59XG4iXX0=