name: Renovate
on:
  workflow_dispatch:
env:
  LOG_LEVEL: debug
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.3.4
        with:
          configurationFile: ./runner-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
