name: Renovate

on:
  workflow_dispatch:

# Declare default permissions as read only.
permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: yarn --cwd .github/ng-renovate install --immutable
        shell: bash

      # Note: Run Renovate outside of Yarn as otherwise we would end up breaking Yarn path
      # resolution due to Yarn setting `YARN_IGNORE_PATH`. This would cause vendored Yarn
      # installations to be ignored and lock file generation for repositories to break.
      - run: .github/ng-renovate/node_modules/.bin/renovate
        env:
          LOG_LEVEL: debug
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_FORK_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
